also adding linting auto-PR for ruff fixes

diff --git a/.github/workflows/lint.yml b/.github/workflows/lint.yml
--- a/.github/workflows/lint.yml
+++ b/.github/workflows/lint.yml
@@ -21,13 +21,41 @@ jobs:
       - name: Install lint tools
         run: |
           python -m pip install --upgrade pip
-          pip install mypy pylint ruff
+          pip install mypy ruff
       - name: Run mypy
         run: |
           mypy --ignore-missing-imports --show-error-codes ${{ inputs.lint-src }}
       - name: Run ruff
         run: |
-          ruff check ${{ inputs.lint-src }}
+          ruff check --fix --unsafe-fixes ${{ inputs.lint-src }}
+      - name: Check for ruff changes
+        id: ruff
+        shell: bash
+        run: |
+          if [[ -n "$(git status --porcelain)" ]]; then
+            echo "Ruff made changes to the code."
+            echo "changed=true" >> "$GITHUB_OUTPUT"
+          else
+            echo "Ruff did not make any changes to the code."
+            echo "changed=false" >> "$GITHUB_OUTPUT"
+          fi
 
+      - name: Create Pull Request
+        if: steps.ruff.outputs.changed == 'true'
+        uses: peter-evans/create-pull-request@v7
+        with:
+          token: ${{ secrets.GITHUB_TOKEN }}
+          title: "${{ env.BRANCH_NAME }} Fix ruff issues"
+          commit-message: ":wrench: Fix ruff issues"
+          body: |
+            Ruff found and fixed lint issues.
+          base: ${{ github.head_ref }} # Creates pull request onto pull request or commit branch
+          branch: ruff/${{ env.BRANCH_NAME }}
+
+      - name: Fail job if fixes were needed
+        if: steps.ruff.outputs.changed == 'true'
+        run: |
+          echo "Ruff fixes were required. Merge the generated PR."
+          exit 1
 
 
